steps:
  # pull secrets
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', '-r','gs://${_MY_BUCKET}/kysa23-service-api/*', '.' ]
  # build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/kysa23-project/kysa23-service-api', '-f', './build/gcp/Dockerfile', '.' ]
  # push
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/kysa23-project/kysa23-service-api' ]
  # deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'kysa23-service-api', '--image', 'gcr.io/kysa23-project/kysa23-service-api', '--region', 'us-central1', '--port', '3000' ]
images:
  - 'gcr.io/kysa23-project/kysa23-service-api'
