### get all
GET http://localhost:3000/register

### get one
GET http://localhost:3000/register/bar@example-com

### create one
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "foo@example.com",
  "name": "string",
  "dob": "string",
  "sex": "m",
  "contact": "string",
  "geo": "string",
  "isMember": false,
  "joins": [
    1,
    2,
    33
  ]
}
